#pragma once

/*Adapted from GLFW3*/

#define MOUSE_CODE_BUTTON_1         0
#define MOUSE_CODE_BUTTON_2         1
#define MOUSE_CODE_BUTTON_3         2
#define MOUSE_CODE_BUTTON_4         3
#define MOUSE_CODE_BUTTON_5         4
#define MOUSE_CODE_BUTTON_6         5
#define MOUSE_CODE_BUTTON_7         6
#define MOUSE_CODE_BUTTON_8         7
#define MOUSE_CODE_BUTTON_LAST      MOUSE_CODE_BUTTON_8
#define MOUSE_CODE_BUTTON_LEFT      MOUSE_CODE_BUTTON_1
#define MOUSE_CODE_BUTTON_RIGHT     MOUSE_CODE_BUTTON_2
#define MOUSE_CODE_BUTTON_MIDDLE    MOUSE_CODE_BUTTON_3